name: Publish to PyPI

on:
  release:
    types: [published]
  # Questo è il pulsante manuale per la nostra situazione
  workflow_dispatch:
    inputs:
      manual_version:
        description: 'Versione da forzare su PyPI (es. 1.5.0)'
        required: true
        default: '1.5.0'

jobs:
  pypi-publish:
    if: github.repository == 'Sei969/qobuz-dl'
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Estrai la versione
      id: extract_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.manual_version }}"
        else
          VERSION=${GITHUB_REF_NAME#v}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "La versione che verrà iniettata è: $VERSION"

    - name: Inietta la versione nel setup.py
      run: |
        sed -i "s/version=['\"].*['\"]/version='${{ env.VERSION }}'/g" setup.py
        echo "Verifica del setup.py aggiornato:"
        grep "version=" setup.py

    - name: Installa i tool di compilazione
      run: python -m pip install --upgrade pip build

    - name: Compila il pacchetto
      run: python -m build

    - name: Pubblica su PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
